[build]
  publish = "_site"
  command = "npm run build"

[[redirects]]
  from = "/email"
  to = "/.netlify/functions/email"
  status = 200

[[redirects]]
  from = "/hello-world"
  to = "/.netlify/functions/hello-world"
  status = 200